baseURL: https://xinweilau.com/
languageCode: en-us
title: Lau Xin Wei
theme: simple-dev-portfolio

params:
    description: An aspiring Full-stack developer and sophomore at Nanyang Technological University, currently pursuing a degree in Computer Science. I am a highly motivated individual who consistently strives to improve my skills, and enjoys creating meaningful and useful solutions that helps tackle problems in our everyday lives.
    preview_url: https://live.staticflickr.com/65535/52278999235_d444f4252e_b.jpg
