name = "Simple Dev Portfolio"
license = "MIT"
licenselink = "https://https://github.com/xinweilau/simple-dev-portfolio/blob/main/LICENSE"
description = "A simple portfolio website made with TailwindCSS"
homepage = "https://xinweilau.com/"
tags = ["Hugo", "TailwindCSS", "developer", "theme"]
features = []
min_version = "0.41.0"

[author]
  name = "Lau Xin Wei"
  homepage = "https://xinweilau.com/"
